name: Load Test
on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Run load test'
        required: false
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  k6_load_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run local k6 test
      uses: k6io/action@v0.1
      with:
        filename: test.js
