name: PRs reviews reminder
on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Run Manually'
        required: false
  schedule:
    - cron: "0 10-17/4 * * 1-5"

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }} # Required
        provider: 'slack' # Required (slack or msteams)
        channel: '#githubactions_notifications' # Optional, eg: #general
        github-provider-map: 'mcdermg:testing,Celestial-Industries:terraform-example-repo,Celestial-Industries:actions_testing' # Optional, eg: "DavideViolante:UEABCDEFG,foobar:UAABCDEFG"
